### ISSUE TITLE
why 

### ISSUE THREAD

**Issue by joaozinhom** [sandov/sway_configs#1]
why the esc change to capslock?

**Comment by sandov** [comment]
Because I use ESC much more often than Caps Lock, so it's better to have it in a place that I can easily reach without having to move my hand from its resting position.

Some of the uses of ESC are:

- Switch back to normal mode when using Vim
- Deselecting options in GUIs and web applications.

**Comment by joaozinhom** [comment]
ok : )

**Comment by joaozinhom** [comment]
maybe woth you try a ergonimic or ortolinear keyboard this solve better than change the layout, like the ctsc40
